# Generated by Django 4.0.3 on 2022-03-30 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LeatherClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('length', models.IntegerField(verbose_name='Длина')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='women.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Женская кожаная одежда',
                'verbose_name_plural': 'Женская кожаная одежда',
                'ordering': ['id'],
            },
        ),
    ]
